### ISSUE TITLE
Reports >> File Reports. Create New Report 'File Information Label'

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#177]
User wants a report to show file information so that they can print it out and paste it on the manila folder of their respective file.

(1) Create a new report in the following format refer attached image. 
(2) It should cover 50% of the A4 Paper i.e. two files' information can be printed on the same paper. 
(3) Attached it to menu Reports >>File Reports.  User can select multiple files to print labels (i.e. Pop up window for user to select files). 
(4) Export to PDF be availabe.

![image](https://cloud.githubusercontent.com/assets/10192106/8816974/cac29eec-3070-11e5-8fa7-7a2c3981b285.png)

**Comment by AAndharia** [comment]
@jmervana - please include this in your estimation today.

**Comment by AAndharia** [comment]
@mnarewec - few questions here 
1. Do we have to implement both functions - Print & Export To PDF or just Export to PDF?
2. What font family & size do you prefer to use? or we should chose on our own to make it fit on page as per requirement?

**Comment by AAndharia** [comment]
@jmervana - Please analyze and estimate

**Comment by jmervana** [comment]
@mnarewec 

what is the name of the pdf file ?

**Comment by mnarewec** [comment]
'FileLabels.Pdf'

**Comment by mnarewec** [comment]
FileLabels. Pdf

**Comment by jmervana** [comment]
@mnarewec 
what about permission to access this report?

**Comment by mnarewec** [comment]
Yes permission

**Comment by AAndharia** [comment]
@mnarewec - for this report we will have to implement pagination to display report in browser, because browser will not be able to handle too much data. For pdf it would download all together.

So here is my suggestion, at any time we display at max 2 reports (like you shown in attached screenshot),  and give pagination. user hit next, they'll see other 2 etc. Unlike any other pagination in grid, user will not be able to change the page size, it will always be 2 hard coded, user can just navigate among pages.

Please suggest.

**Comment by mnarewec** [comment]
Yes, that will be ideal.

**Comment by mnarewec** [comment]
This is done.
