### ISSUE TITLE
What is the recommended size of theLogo

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#71]
So that it can appear nicely on the bills?

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
according to me, Height will be 70 PX & width will be 225 PX will be best for bills.
please suggest.

**Comment by mnarewec** [comment]
Thanks will try this out and revert.

**Comment by mnarewec** [comment]
@jmervana , even though I change to 70 and 225 the logo on the PDF File is still blurry. Please can you advise what is the size of the Logo you design on the PDF?

**Comment by jmervana** [comment]
@mnarewec 
we can give max height and max width to logo if the size of logo is bigger than max width or max height at that time logo will appear as per our fixed size otherwise it takes its original size.

**Comment by AAndharia** [comment]
@japan - please make height/width auto, so that it would show full image uploaded without blur.

Reference Discussion 
------
Marsh: The logo issue can Japan go as his recommendation because the current KBS PDF logo that will go to the user's clients looking blurry and I will get alot of hear bashing from this particular user
Amit: which # ?
Marsh: #71, #68,#81
Amit: we'll do it like this..
if you upload 70 X 225 logo
it would not blurr
if size is different, then it would blurr
alright?
Sent at 15:46 on Tuesday
Marsh: ok
Amit: ok, i'll ask Japan to get it done
and send you new release
Marsh: lets see, but some clients will have the width as 255
what about 255 by 255, any size below will NOT blur but any size above will blur, so if I upload 70 by 255 it will not blur
Amit: technically its not possible
image always blurr if their aspect ratio is not same as aspect ratio of size given in html
we are using iTextSharp
and its limitation
that it can't use max height/max width
Marsh: what about the HTML size is AUTO i.e. not fixed
Amit: then it would show size whatever is actual size of image
but if someone upload 500 x 500 it would show 500 x 500 big logo
Marsh: will it not blur?
Amit: no blurr
Marsh: the current KBS size is definitely not Auto because its blur
Amit: you need it to be auto?
we can do that..
we get fixed size to avoid showing big logo if someone by mistake upload a large logo
Marsh: All I want is for the image not to blur
Amit: 2 opttions
you can choose one
and we'll do it
1. make it auto
2. make it fixed size
Marsh: which want will not blur irrespective of size?
Amit: 1.
Marsh: Okay option 1 then
Amit: alright.
will do that, and japan will send you it next release

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
Done.

I have put restriction to upload logo upto maximum size of 300*300.
and logo will display with its original size at every place.

**Comment by mnarewec** [comment]
Thank you. This done
